# Generated by Django 5.2.1 on 2025-05-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField()),
                ('status', models.CharField(choices=[('done', 'Done'), ('current', 'Current'), ('upcoming', 'Upcoming'), ('tba', 'TBA')], max_length=10)),
            ],
        ),
    ]
